# Trials of pruning techniques

In [1]:
%load_ext autoreload
%autoreload 2

from torch import nn
import torch.nn.functional as F
from torch import from_numpy
import sys
import numpy as np
if "../" not in sys.path:
    sys.path.insert(0, '../')
    sys.path.insert(0, '../scripts')
import scripts.utils.pruning as pruning
from scripts.utils.common import set_seed
from scripts.utils.model import get_prunable

/home/s41m0n/Desktop/intellect/.venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
class Example(nn.Module):
    def __init__(self):
        super(Example, self).__init__()
        self.fc1 = nn.Linear(10, 5)
        self.fc2 = nn.Linear(5, 5)
        self.fc3 = nn.Linear(5, 1)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

In [3]:
set_seed()
X = from_numpy(np.random.rand(2,10)).float()

## Globally Trials

In [4]:
set_seed()

model = Example()
prev = model(X)
pruning.globally_structured_connections_l1(model, get_prunable(model), 0.5)
post = model(X)

print(model.fc1.weight_mask)
print(model.fc2.weight_mask)
print(model.fc3.weight_mask)
print(prev)
print(post)

2023-09-20 15:36:33,411 - pruning - INFO - Globally Pruning using amount=0.5 method=LnStructured and n.len(layers)=3 layers


tensor([[0., 1., 1., 1., 1., 0., 1., 1., 0., 0.],
        [0., 1., 1., 1., 1., 0., 1., 1., 0., 0.],
        [0., 1., 1., 1., 1., 0., 1., 1., 0., 0.],
        [0., 1., 1., 1., 1., 0., 1., 1., 0., 0.],
        [0., 1., 1., 1., 1., 0., 1., 1., 0., 0.]])
tensor([[1., 0., 1., 1., 1.],
        [1., 0., 1., 1., 1.],
        [1., 0., 1., 1., 1.],
        [1., 0., 1., 1., 1.],
        [1., 0., 1., 1., 1.]])
tensor([[0., 0., 0., 0., 0.]])
tensor([[0.0219],
        [0.0100]], grad_fn=<AddmmBackward0>)
tensor([[0.1639],
        [0.1639]], grad_fn=<AddmmBackward0>)


In [30]:
set_seed()
model = Example()
prev = model(X)
pruning.globally_structured_connections_random(model, get_prunable(model), 0.5)
post = model(X)
print(model.fc1.weight_mask)
print(model.fc2.weight_mask)
print(model.fc3.weight_mask)
print(prev)
print(post)

2023-09-15 12:28:13,107 - pruning - INFO - Globally Pruning using amount=0.5 method=LnStructured and n.len(layers)=3 layers


tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[0., 0., 0., 0., 0.]])
tensor([[0.0219],
        [0.0100]], grad_fn=<AddmmBackward0>)
tensor([[0.1639],
        [0.1639]], grad_fn=<AddmmBackward0>)


In [9]:
set_seed()
model = Example()
pruning.globally_structured_neurons_l1(model, get_prunable(model), 0.5)
print(model.fc1.weight_mask)
print(model.fc2.weight_mask)
print(model.fc3.weight_mask)

2023-09-15 12:12:47,830 - pruning - INFO - Globally Pruning using amount=0.5 method=LnStructured and n.len(layers)=3 layers


tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0.]])
tensor([[0., 0., 0., 0., 0.]])


In [5]:
set_seed()
model = Example()
pruning.globally_structured_neurons_random(model, get_prunable(model), 0.5)
print(model.fc1.weight_mask)
print(model.fc2.weight_mask)
print(model.fc3.weight_mask)

2023-09-15 12:15:26,152 - pruning - INFO - Globally Pruning using amount=0.5 method=RandomStructured and n.len(layers)=3 layers


tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[1., 1., 1., 1., 1.]])


In [6]:
set_seed()
model = Example()
pruning.globally_unstructured_connections_l1(model, get_prunable(model), 0.5)
print(model.fc1.weight_mask)
print(model.fc2.weight_mask)
print(model.fc3.weight_mask)

2023-09-15 12:15:43,562 - pruning - INFO - Globally Pruning using amount=0.5 method=L1Unstructured and n.len(layers)=3 layers


tensor([[0., 0., 1., 1., 0., 0., 0., 1., 0., 0.],
        [0., 0., 1., 1., 0., 0., 0., 1., 1., 0.],
        [0., 1., 0., 1., 0., 0., 1., 1., 1., 0.],
        [0., 1., 1., 0., 1., 1., 1., 1., 0., 0.],
        [0., 0., 0., 1., 1., 0., 1., 1., 0., 0.]])
tensor([[1., 0., 1., 1., 1.],
        [1., 1., 1., 0., 1.],
        [0., 0., 0., 1., 1.],
        [1., 0., 0., 1., 1.],
        [1., 0., 1., 0., 1.]])
tensor([[0., 0., 1., 0., 1.]])


In [7]:
set_seed()
model = Example()
pruning.globally_unstructured_connections_random(model, get_prunable(model), 0.5)
print(model.fc1.weight_mask)
print(model.fc2.weight_mask)
print(model.fc3.weight_mask)

2023-09-15 12:15:55,758 - pruning - INFO - Globally Pruning using amount=0.5 method=RandomUnstructured and n.len(layers)=3 layers


tensor([[1., 0., 0., 0., 0., 0., 1., 0., 1., 1.],
        [1., 1., 1., 1., 1., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 1.],
        [0., 0., 1., 1., 1., 1., 1., 0., 0., 1.],
        [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.]])
tensor([[0., 0., 0., 1., 1.],
        [0., 0., 1., 1., 0.],
        [0., 1., 1., 1., 0.],
        [1., 1., 0., 0., 1.],
        [0., 1., 0., 0., 1.]])
tensor([[1., 0., 1., 0., 0.]])


In [16]:
set_seed()
model = Example()
prev = model(X)
pruning.globally_structured_neurons_activation_l1(model, get_prunable(model), 0.5, X)
post = model(X)
print(model.fc1.weight_mask)
print(model.fc2.weight_mask)
print(model.fc3.weight_mask)
print(prev)
print(post)

2023-09-15 12:21:44,490 - pruning - INFO - Globally Pruning Neurons looking for activation, length of subset provided len(subset_features)=0 amount=0.5 and n.len(layers)=3 layers n=1
2023-09-15 12:21:44,490 - pruning - INFO - Getting neurons' activations
2023-09-15 12:21:44,493 - pruning - INFO - Globally Pruning using amount=0.5 method=LnStructured and n.len(layers)=3 layers


torch.Size([2, 5])
torch.Size([2, 5])
torch.Size([2, 5])
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])
tensor([[1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[0., 0., 0., 0., 0.]])
tensor([[0.0640],
        [0.0640]], grad_fn=<AddmmBackward0>)
tensor([[0.1639],
        [0.1639]], grad_fn=<AddmmBackward0>)


## Locally Trials

In [10]:
set_seed()
model = Example()
layers = get_prunable(model)
pruning.locally_structured_connections_l1(model, layers, [0.5]*len(layers))
print(model.fc1.weight_mask)
print(model.fc2.weight_mask)
print(model.fc3.weight_mask)

2023-09-15 12:17:00,371 - pruning - INFO - Locally Pruning Connections structured=True using amount=[0.5, 0.5, 0.5] n=1 dim=1 and n.len(layers)=3


tensor([[0., 1., 1., 1., 0., 0., 1., 1., 0., 0.],
        [0., 1., 1., 1., 0., 0., 1., 1., 0., 0.],
        [0., 1., 1., 1., 0., 0., 1., 1., 0., 0.],
        [0., 1., 1., 1., 0., 0., 1., 1., 0., 0.],
        [0., 1., 1., 1., 0., 0., 1., 1., 0., 0.]])
tensor([[1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1.]])
tensor([[0., 0., 1., 1., 1.]])


In [11]:
set_seed()
model = Example()
layers = get_prunable(model)
pruning.locally_structured_connections_random(model, layers, [0.5]*len(layers))
print(model.fc1.weight_mask)
print(model.fc2.weight_mask)
print(model.fc3.weight_mask)

2023-09-15 12:17:36,416 - pruning - INFO - Locally Pruning Connections structured=True using amount=[0.5, 0.5, 0.5] n=0 dim=1 and n.len(layers)=3


tensor([[1., 1., 1., 0., 0., 1., 0., 0., 0., 1.],
        [1., 1., 1., 0., 0., 1., 0., 0., 0., 1.],
        [1., 1., 1., 0., 0., 1., 0., 0., 0., 1.],
        [1., 1., 1., 0., 0., 1., 0., 0., 0., 1.],
        [1., 1., 1., 0., 0., 1., 0., 0., 0., 1.]])
tensor([[1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1.]])
tensor([[0., 0., 1., 1., 1.]])


In [12]:
set_seed()
model = Example()
layers = get_prunable(model)
pruning.locally_structured_neurons_l1(model, layers, [0.5]*len(layers))
print(model.fc1.weight_mask)
print(model.fc2.weight_mask)
print(model.fc3.weight_mask)

2023-09-15 12:17:54,746 - pruning - INFO - Locally Pruning Neurons structured=True using amount=[0.5, 0.5, 0.5] n=1 dim=0 and n.len(layers)=3


tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])
tensor([[1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[1., 1., 1., 1., 1.]])


In [13]:
set_seed()
model = Example()
layers = get_prunable(model)
pruning.locally_structured_neurons_random(model, layers, [0.5]*len(layers))
print(model.fc1.weight_mask)
print(model.fc2.weight_mask)
print(model.fc3.weight_mask)

2023-09-15 12:18:00,891 - pruning - INFO - Locally Pruning Neurons structured=True using amount=[0.5, 0.5, 0.5] n=0 dim=0 and n.len(layers)=3


tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1.]])
tensor([[1., 1., 1., 1., 1.]])
